#!/usr/bin/env node
/** Reads store HTML files and writes them into src/pages.ts as exported strings. */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const storeDir = path.join(__dirname, '..', '..', 'store');

const pages = {
  homepage: fs.readFileSync(path.join(storeDir, 'index.html'), 'utf-8'),
  aboutPage: fs.readFileSync(path.join(storeDir, 'about', 'index.html'), 'utf-8'),
  getStartedPage: fs.readFileSync(path.join(storeDir, 'get-started', 'index.html'), 'utf-8'),
  consolePage: fs.readFileSync(path.join(storeDir, 'console', 'index.html'), 'utf-8'),
  agentDetailPage: fs.readFileSync(path.join(storeDir, 'agents', 'detail.html'), 'utf-8'),
  widgetJs: fs.readFileSync(path.join(storeDir, 'widget.js'), 'utf-8'),
  authWidgetJs: fs.readFileSync(path.join(storeDir, 'auth-widget.js'), 'utf-8'),
  developerProfilePage: fs.readFileSync(path.join(storeDir, 'developers', 'profile.html'), 'utf-8'),
};

let out = '// Auto-generated by build.js — do not edit manually\n';
for (const [name, html] of Object.entries(pages)) {
  out += `export const ${name} = ${JSON.stringify(html)};\n`;
}

fs.writeFileSync(path.join(__dirname, 'src', 'pages.ts'), out);
console.log('Generated src/pages.ts with', Object.keys(pages).length, 'pages');
