#!/usr/bin/env node
/** Reads store HTML files and writes them into src/pages.ts as exported strings. */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const storeDir = path.join(__dirname, "..", "..", "store");

const pages = {
	homepage: fs.readFileSync(path.join(storeDir, "index.html"), "utf-8"),
	aboutPage: fs.readFileSync(
		path.join(storeDir, "about", "index.html"),
		"utf-8",
	),
	getStartedPage: fs.readFileSync(
		path.join(storeDir, "get-started", "index.html"),
		"utf-8",
	),
	skillsPage: fs.readFileSync(
		path.join(storeDir, "skills", "index.html"),
		"utf-8",
	),
	skillMcpOperatorPage: fs.readFileSync(
		path.join(storeDir, "skills", "proagentstore-mcp-operator", "index.html"),
		"utf-8",
	),
	browserRuntimeDocsPage: fs.readFileSync(
		path.join(storeDir, "docs", "browser-runtime", "index.html"),
		"utf-8",
	),
	mcpDocsPage: fs.readFileSync(
		path.join(storeDir, "docs", "mcp", "index.html"),
		"utf-8",
	),
	consolePage: fs.readFileSync(
		path.join(storeDir, "console", "index.html"),
		"utf-8",
	),
	consoleCss: fs.readFileSync(
		path.join(storeDir, "console", "console.css"),
		"utf-8",
	),
	consoleCoreJs: fs.readFileSync(
		path.join(storeDir, "console", "console-core.js"),
		"utf-8",
	),
	consoleInstancesJs: fs.readFileSync(
		path.join(storeDir, "console", "console-instances.js"),
		"utf-8",
	),
	consoleAgentDataJs: fs.readFileSync(
		path.join(storeDir, "console", "console-agent-data.js"),
		"utf-8",
	),
	consoleProfileJs: fs.readFileSync(
		path.join(storeDir, "console", "console-profile.js"),
		"utf-8",
	),
	consoleUtilsInitJs: fs.readFileSync(
		path.join(storeDir, "console", "console-utils-init.js"),
		"utf-8",
	),
	agentDetailPage: fs.readFileSync(
		path.join(storeDir, "agents", "detail.html"),
		"utf-8",
	),
	widgetJs: fs.readFileSync(path.join(storeDir, "widget.js"), "utf-8"),
	authWidgetJs: fs.readFileSync(path.join(storeDir, "auth-widget.js"), "utf-8"),
	adminPage: fs.readFileSync(path.join(storeDir, "admin", "index.html"), "utf-8"),
	notFoundPage: fs.readFileSync(path.join(storeDir, "404.html"), "utf-8"),
	changelogPage: fs.readFileSync(path.join(storeDir, "changelog", "index.html"), "utf-8"),
	openapiYaml: fs.readFileSync(path.join(storeDir, "openapi.yaml"), "utf-8"),
	llmsTxt: fs.readFileSync(path.join(storeDir, "llms.txt"), "utf-8"),
	llmsFullTxt: fs.readFileSync(path.join(storeDir, "llms-full.txt"), "utf-8"),
	skillsJson: fs.readFileSync(path.join(storeDir, "skills.json"), "utf-8"),
	mcpServerJson: fs.readFileSync(path.join(storeDir, ".well-known", "mcp-server.json"), "utf-8"),
	developerProfilePage: fs.readFileSync(
		path.join(storeDir, "developers", "profile.html"),
		"utf-8",
	),
};

// Binary assets (base64 encoded)
const brandDir = path.join(__dirname, "..", "..", "brand", "assets");
const binaries = {};
for (const size of [16, 32, 48, 64, 128, 180, 192, 512]) {
	const p = path.join(brandDir, `icon-${size}.png`);
	if (fs.existsSync(p)) binaries[`icon${size}`] = fs.readFileSync(p).toString("base64");
}
const ogPath = path.join(brandDir, "og-image.png");
if (fs.existsSync(ogPath)) binaries.ogImage = fs.readFileSync(ogPath).toString("base64");
const faviconSvg = fs.existsSync(path.join(brandDir, "favicon.svg"))
	? fs.readFileSync(path.join(brandDir, "favicon.svg"), "utf-8") : "";
const manifestJson = fs.readFileSync(path.join(storeDir, "manifest.json"), "utf-8");

let out = "// Auto-generated by build.js — do not edit manually\n";
for (const [name, html] of Object.entries(pages)) {
	out += `export const ${name} = ${JSON.stringify(html)};\n`;
}
out += `export const faviconSvg = ${JSON.stringify(faviconSvg)};\n`;
out += `export const manifestJson = ${JSON.stringify(manifestJson)};\n`;
for (const [name, b64] of Object.entries(binaries)) {
	out += `export const ${name} = "${b64}";\n`;
}

fs.writeFileSync(path.join(__dirname, "src", "pages.ts"), out);
console.log("Generated src/pages.ts with", Object.keys(pages).length, "pages +", Object.keys(binaries).length, "assets");
