name = "proagentstore-AGENTNAME"
main = "src/index.ts"
compatibility_date = "2026-01-01"
compatibility_flags = ["nodejs_compat"]

[[routes]]
pattern = "AGENTNAME.proagentstore.online/*"
zone_name = "proagentstore.online"

[ai]
binding = "AI"

[triggers]
crons = ["0 8 * * *"]
