-- Record WHOSE ARITHMETIC produced a cost figure (#267).
--
-- CORRECTED IN PLACE at #347. This comment used to say the coding Engine's figure "is the real
-- thing rather than our arithmetic". It is not, and that sentence is what turned a provenance
-- flag into a licence to enforce: #343's $50 circuit breaker fired on $48.76 of engine turns run
-- on a Claude subscription, over a bill that did not exist.
--
-- Anthropic's docs (https://code.claude.com/docs/en/costs) are explicit: Claude Code "computes the
-- dollar figure locally from token counts priced at standard list rates, so it doesn't reflect
-- promotional pricing or contracted discounts and may differ from your actual bill", and Max/Pro
-- subscribers "have usage included in their subscription, so the session cost figure isn't
-- relevant for billing purposes". `total_cost_usd` is tokens × list price — the same construction
-- as lib/ai-pricing.ts, run by a different process.
--
-- So EVERY ai_usage row carries an estimate, and this column records only which process estimated
-- it. That is still worth knowing (the CLI has the exact per-turn token split and model, so its
-- figure is the better estimate), but it carries no authority about money.
--
-- NULL  — we computed it from lib/ai-pricing.ts. True for every pre-existing row, so no backfill.
-- 'reported' — the provider's own CLI computed it.
--
-- Whether a figure is money at all is `payer` (migration 0092), which is a different question
-- this column was wrongly read as answering.
ALTER TABLE ai_usage ADD COLUMN cost_source TEXT;
